### ISSUE TITLE
Zet de inputs in/onder de labels

### ISSUE THREAD

**Issue by zoepje** [Hadil66/component-building-block#2]
https://github.com/Hadil66/component-building-block/blob/2e282c5a1e2fa1fe7964c2d1528fc486aa9a3eb7/src/lib/molecules/Filters.svelte#L1-L13

Ik snap dat je de inputs buiten beeld wil houden maar als je de inputs er bij zet kun je nog steeds met de css die je nu hebt ervoor kunnen zorgen dat ze buiten beeld zijn.

**Comment by Hadil66** [comment]
Slim! Ik had er niet aan gedacht om het in de CSS te verbergen.
