### ISSUE TITLE
Zou je dit niet makkelijker kunnen schrijven

### ISSUE THREAD

**Issue by zoepje** [Hadil66/component-building-block#3]
https://github.com/Hadil66/component-building-block/blob/903cb9722a72d2362ecf9231f7c36a24114ea40e/src/lib/molecules/Filters.svelte#L18-L22

Volgens mij kun je hier gewoon `input[type= "radio"]:checked` zetten

**Comment by Hadil66** [comment]
Dankjewel! Ik heb het inderdaad makkelijker kunnen schrijven. 
Ik heb het op deze manier gedaan!
``` <button
      on:mouseover={() => activeFilter.set("Glass")}
      on:mouseleave={() => ($activeFilter = "*")}>Glass</button
    >
  </li>
```
